name: C/C++ Build
on: [workflow_dispatch] #команда запуска workflow только в ручному режиме

env:
  source_file: ./Console_Application_test/Console_Application_test/Console_Application_test.cpp
  
# Запуск рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельн
jobs:
  print_test:  # название дожоба - "ptint_test"
    #определяет, под какой системой будет работать данные workflow 
    runs-on: ubuntu-latest 
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: ls -a
        run:  ls -a
      - name: create folder 
        run:  mkdir build
      - name: build gcc
        run:  gcc ${{source_file}} -o ./build/run
      - name: ls -a
        run:  |
            ls -a
            echo -----------------
      - name: ls -a build
        run:  |
            ls -a build
            echo -----------------
      - name: use artifact
        uses: actions/upload-artifact@v3
        with:
            name: art1
            path: ./build/run
