name: C/C++ CI

on: [workflow_dispatch]
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
    - uses: actions/checkout@v3
    - name: ls -a
      run: ls -a
      
    #- name: build_gcc
      #run: gcc -Wall 
    
    #- name: configure
    #  run: ./configure
    #- name: make
    #  run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    # run: make distcheck
