name: C/C++ CI

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: clone repo
      uses: actions/checkout@v3
    - name:  test escape sequences 
      run: |
        echo 1324
        echo C:
        echo &#58
        echo A&#58
   # - name: configure
   #   run: ./configure
   # - name: ls -a
   #   run: la -a
    #- name: make
      #run: make
    #- name: make check
      #run: make check
    #- name: make distcheck
      #run: make distcheck
